[tmux]
name = "TMux"
shortcuts = [ 
  { name = "create window", cmd = ["CTRL+b", "w"] },
  { name = "split horizontally", cmd = ["CTRL+b", "\""] },
  { name = "split vertically", cmd = ["CTRL+b", "%"] },
]

[nvim]
name = "NVIM"
shortcuts = [ 
  { name = "jump to top", cmd = ["g", "g"] },
  { name = "jump to bottom", cmd = ["G"] }
]

[shell]
name = "Shell"
shortcuts = [ 
  { name = "jump to line start", cmd = ["CTRL+a"] },
  { name = "jump to line end", cmd = ["CTRL+e"] }
]

